// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechVault.API.Data;

#nullable disable

namespace TechVault.API.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TechVault.API.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("IsDefaultBilling")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDefaultShipping")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Line1")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Line2")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Region")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("TechVault.API.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("IdentityUserId", "ProductId")
                        .IsUnique();

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("TechVault.API.Models.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("DiscountType")
                        .HasColumnType("int");

                    b.Property<decimal>("DiscountValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("MinOrderValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Coupons");
                });

            modelBuilder.Entity("TechVault.API.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Notebooks and ultrabooks",
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Laptops",
                            Slug = "laptops"
                        },
                        new
                        {
                            Id = 2,
                            Description = "CPUs, GPUs, memory, storage",
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "PC Components",
                            Slug = "pc-components"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Keyboards, mice, audio",
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "Peripherals",
                            Slug = "peripherals"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Displays and panels",
                            DisplayOrder = 4,
                            IsActive = true,
                            Name = "Monitors",
                            Slug = "monitors"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Routers, switches, cables",
                            DisplayOrder = 5,
                            IsActive = true,
                            Name = "Networking",
                            Slug = "networking"
                        });
                });

            modelBuilder.Entity("TechVault.API.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BillingCity")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("BillingCountry")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("BillingFullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("BillingLine1")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("BillingLine2")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("BillingPostalCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("BillingRegion")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("CouponCode")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ConfirmedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeliveredAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime?>("PaidAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("TrackingUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.Property<DateTime>("PlacedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ProcessingAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ShippedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ShippingAddressId")
                        .HasColumnType("int");

                    b.Property<decimal>("ShippingAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShippingCity")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ShippingCountry")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ShippingFullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ShippingLine1")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("ShippingLine2")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("ShippingPhone")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("ShippingPostalCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("ShippingRegion")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("IdentityUserId")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("IdentityUserId");

                    b.HasIndex("PlacedAtUtc");

                    b.HasIndex("ShippingAddressId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Status");

                    b.HasIndex("IdentityUserId", "Status");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("TechVault.API.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("ProductSku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("TechVault.API.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("AmountCents")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("ExternalChargeId")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ExternalPaymentId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalPaymentId")
                        .IsUnique();

                    b.HasIndex("OrderId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("TechVault.API.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal?>("CompareAtPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPublished")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(280)
                        .HasColumnType("varchar(280)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Brand");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("CategoryId", "IsPublished");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Name", "Description")
                        .HasAnnotation("MySql:FullTextIndex", true);

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Brand = "TechVault",
                            CategoryId = 1,
                            CompareAtPrice = 1099.99m,
                            CreatedAtUtc = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "/images/products/probook-14.jpg",
                            IsPublished = true,
                            Name = "TechVault ProBook 14",
                            Price = 999.99m,
                            ShortDescription = "14\" business ultrabook",
                            Sku = "TV-LAP-001",
                            Slug = "techvault-probook-14",
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Brand = "TechVault",
                            CategoryId = 1,
                            CreatedAtUtc = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "/images/products/blade-16.jpg",
                            IsPublished = true,
                            Name = "TechVault Blade 16",
                            Price = 1899.00m,
                            ShortDescription = "16\" creator laptop",
                            Sku = "TV-LAP-002",
                            Slug = "techvault-blade-16",
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Brand = "TechVault",
                            CategoryId = 1,
                            CompareAtPrice = 849.00m,
                            CreatedAtUtc = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "/images/products/air-13.jpg",
                            IsPublished = true,
                            Name = "TechVault Air 13",
                            Price = 799.00m,
                            ShortDescription = "13\" lightweight daily driver",
                            Sku = "TV-LAP-003",
                            Slug = "techvault-air-13",
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            Brand = "TechVault",
                            CategoryId = 1,
                            CreatedAtUtc = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "/images/products/station-17.jpg",
                            IsPublished = true,
                            Name = "TechVault Station 17",
                            Price = 2499.00m,
                            ShortDescription = "17\" workstation",
                            Sku = "TV-LAP-004",
                            Slug = "techvault-station-17",
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = 5,
                            IsDeleted = false,
                            Brand = "NovaGraph",
                            CategoryId = 2,
                            CompareAtPrice = 749.00m,
                            CreatedAtUtc = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "/images/products/gpu-780.jpg",
                            IsPublished = true,
                            Name = "NovaGraph RTX 780",
                            Price = 699.00m,
                            ShortDescription = "High-end graphics card",
                            Sku = "TV-GPU-001",
                            Slug = "novagraph-rtx-780",
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 6,
                            IsDeleted = false,
                            Brand = "CorePeak",
                            CategoryId = 2,
                            CreatedAtUtc = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "/images/products/cpu-i9.jpg",
                            IsPublished = true,
                            Name = "CorePeak i9-14900K",
                            Price = 549.00m,
                            ShortDescription = "Desktop CPU unlocked",
                            Sku = "TV-CPU-001",
                            Slug = "corepeak-i9-14900k",
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 7,
                            IsDeleted = false,
                            Brand = "RAMBurst",
                            CategoryId = 2,
                            CompareAtPrice = 149.99m,
                            CreatedAtUtc = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "/images/products/ram-32gb.jpg",
                            IsPublished = true,
                            Name = "RAMBurst DDR5 32GB Kit",
                            Price = 129.99m,
                            ShortDescription = "2x16GB DDR5-6000",
                            Sku = "TV-RAM-001",
                            Slug = "ramburst-ddr5-32gb",
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 8,
                            IsDeleted = false,
                            Brand = "FlashForge",
                            CategoryId = 2,
                            CreatedAtUtc = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "/images/products/ssd-2tb.jpg",
                            IsPublished = true,
                            Name = "FlashForge NVMe 2TB",
                            Price = 179.00m,
                            ShortDescription = "PCIe Gen4 SSD",
                            Sku = "TV-SSD-001",
                            Slug = "flashforge-nvme-2tb",
                            StockQuantity = 55
                        },
                        new
                        {
                            Id = 9,
                            IsDeleted = false,
                            Brand = "KeyForge",
                            CategoryId = 3,
                            CompareAtPrice = 139.00m,
                            CreatedAtUtc = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "/images/products/kb-rgb.jpg",
                            IsPublished = true,
                            Name = "KeyForge Mechanical RGB",
                            Price = 119.00m,
                            ShortDescription = "TKL mechanical keyboard",
                            Sku = "TV-KB-001",
                            Slug = "keyforge-mechanical-rgb",
                            StockQuantity = 80
                        },
                        new
                        {
                            Id = 10,
                            IsDeleted = false,
                            Brand = "GlideAir",
                            CategoryId = 3,
                            CreatedAtUtc = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "/images/products/mouse-wl.jpg",
                            IsPublished = true,
                            Name = "GlideAir Wireless Mouse",
                            Price = 59.99m,
                            ShortDescription = "Ergonomic wireless mouse",
                            Sku = "TV-MS-001",
                            Slug = "glideair-wireless-mouse",
                            StockQuantity = 120
                        },
                        new
                        {
                            Id = 11,
                            IsDeleted = false,
                            Brand = "SoundArc",
                            CategoryId = 3,
                            CompareAtPrice = 99.00m,
                            CreatedAtUtc = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "/images/products/headset.jpg",
                            IsPublished = true,
                            Name = "SoundArc 7.1 Headset",
                            Price = 89.00m,
                            ShortDescription = "USB gaming headset",
                            Sku = "TV-HS-001",
                            Slug = "soundarc-71-headset",
                            StockQuantity = 70
                        },
                        new
                        {
                            Id = 12,
                            IsDeleted = false,
                            Brand = "ClearView",
                            CategoryId = 3,
                            CreatedAtUtc = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "/images/products/webcam.jpg",
                            IsPublished = true,
                            Name = "ClearView 4K Webcam",
                            Price = 129.00m,
                            ShortDescription = "Auto-focus conference cam",
                            Sku = "TV-WC-001",
                            Slug = "clearview-4k-webcam",
                            StockQuantity = 45
                        },
                        new
                        {
                            Id = 13,
                            IsDeleted = false,
                            Brand = "PixelPro",
                            CategoryId = 4,
                            CompareAtPrice = 229.00m,
                            CreatedAtUtc = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "/images/products/mon-24.jpg",
                            IsPublished = true,
                            Name = "PixelPro 24\" FHD",
                            Price = 199.00m,
                            ShortDescription = "1080p 144Hz IPS",
                            Sku = "TV-MON-001",
                            Slug = "pixelpro-24-fhd",
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 14,
                            IsDeleted = false,
                            Brand = "PixelPro",
                            CategoryId = 4,
                            CreatedAtUtc = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "/images/products/mon-27.jpg",
                            IsPublished = true,
                            Name = "PixelPro 27\" QHD",
                            Price = 349.00m,
                            ShortDescription = "1440p 165Hz IPS",
                            Sku = "TV-MON-002",
                            Slug = "pixelpro-27-qhd",
                            StockQuantity = 35
                        },
                        new
                        {
                            Id = 15,
                            IsDeleted = false,
                            Brand = "PixelPro",
                            CategoryId = 4,
                            CompareAtPrice = 649.00m,
                            CreatedAtUtc = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "/images/products/mon-32.jpg",
                            IsPublished = true,
                            Name = "PixelPro 32\" 4K",
                            Price = 599.00m,
                            ShortDescription = "4K HDR creator panel",
                            Sku = "TV-MON-003",
                            Slug = "pixelpro-32-4k",
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 16,
                            IsDeleted = false,
                            Brand = "PixelPro",
                            CategoryId = 4,
                            CreatedAtUtc = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "/images/products/mon-portable.jpg",
                            IsPublished = true,
                            Name = "TravelPanel 15\" USB-C",
                            Price = 249.00m,
                            ShortDescription = "Portable USB-C monitor",
                            Sku = "TV-MON-004",
                            Slug = "travelpanel-15-usbc",
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 17,
                            IsDeleted = false,
                            Brand = "LinkHub",
                            CategoryId = 5,
                            CompareAtPrice = 299.00m,
                            CreatedAtUtc = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "/images/products/router.jpg",
                            IsPublished = true,
                            Name = "LinkHub AX6000 Router",
                            Price = 279.00m,
                            ShortDescription = "Wi-Fi 6E router",
                            Sku = "TV-NET-001",
                            Slug = "linkhub-ax6000-router",
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 18,
                            IsDeleted = false,
                            Brand = "LinkHub",
                            CategoryId = 5,
                            CreatedAtUtc = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "/images/products/switch.jpg",
                            IsPublished = true,
                            Name = "LinkHub 8-Port Switch",
                            Price = 39.99m,
                            ShortDescription = "Gigabit unmanaged switch",
                            Sku = "TV-NET-002",
                            Slug = "linkhub-8port-switch",
                            StockQuantity = 90
                        },
                        new
                        {
                            Id = 19,
                            IsDeleted = false,
                            Brand = "LinkHub",
                            CategoryId = 5,
                            CompareAtPrice = 359.00m,
                            CreatedAtUtc = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "/images/products/mesh.jpg",
                            IsPublished = true,
                            Name = "LinkHub Mesh Trio",
                            Price = 329.00m,
                            ShortDescription = "Whole-home mesh Wi-Fi",
                            Sku = "TV-NET-003",
                            Slug = "linkhub-mesh-trio",
                            StockQuantity = 22
                        },
                        new
                        {
                            Id = 20,
                            IsDeleted = false,
                            Brand = "CableCraft",
                            CategoryId = 5,
                            CreatedAtUtc = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "/images/products/cables.jpg",
                            IsPublished = true,
                            Name = "CableCraft Cat6 Kit",
                            Price = 24.99m,
                            ShortDescription = "25ft patch cables (5-pack)",
                            Sku = "TV-NET-004",
                            Slug = "cablecraft-cat6-kit",
                            StockQuantity = 200
                        });
                });

            modelBuilder.Entity("TechVault.API.Models.ProductTag", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ProductTags");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            TagId = 2
                        },
                        new
                        {
                            ProductId = 1,
                            TagId = 6
                        },
                        new
                        {
                            ProductId = 2,
                            TagId = 1
                        },
                        new
                        {
                            ProductId = 2,
                            TagId = 6
                        },
                        new
                        {
                            ProductId = 3,
                            TagId = 5
                        },
                        new
                        {
                            ProductId = 3,
                            TagId = 3
                        },
                        new
                        {
                            ProductId = 4,
                            TagId = 2
                        },
                        new
                        {
                            ProductId = 4,
                            TagId = 6
                        },
                        new
                        {
                            ProductId = 5,
                            TagId = 1
                        },
                        new
                        {
                            ProductId = 5,
                            TagId = 4
                        },
                        new
                        {
                            ProductId = 6,
                            TagId = 2
                        },
                        new
                        {
                            ProductId = 6,
                            TagId = 6
                        },
                        new
                        {
                            ProductId = 7,
                            TagId = 5
                        },
                        new
                        {
                            ProductId = 7,
                            TagId = 6
                        },
                        new
                        {
                            ProductId = 8,
                            TagId = 5
                        },
                        new
                        {
                            ProductId = 8,
                            TagId = 6
                        },
                        new
                        {
                            ProductId = 9,
                            TagId = 1
                        },
                        new
                        {
                            ProductId = 9,
                            TagId = 4
                        },
                        new
                        {
                            ProductId = 10,
                            TagId = 3
                        },
                        new
                        {
                            ProductId = 10,
                            TagId = 5
                        },
                        new
                        {
                            ProductId = 11,
                            TagId = 1
                        },
                        new
                        {
                            ProductId = 11,
                            TagId = 4
                        },
                        new
                        {
                            ProductId = 12,
                            TagId = 2
                        },
                        new
                        {
                            ProductId = 12,
                            TagId = 3
                        },
                        new
                        {
                            ProductId = 13,
                            TagId = 1
                        },
                        new
                        {
                            ProductId = 13,
                            TagId = 5
                        },
                        new
                        {
                            ProductId = 14,
                            TagId = 1
                        },
                        new
                        {
                            ProductId = 14,
                            TagId = 6
                        },
                        new
                        {
                            ProductId = 15,
                            TagId = 2
                        },
                        new
                        {
                            ProductId = 15,
                            TagId = 6
                        },
                        new
                        {
                            ProductId = 16,
                            TagId = 3
                        },
                        new
                        {
                            ProductId = 16,
                            TagId = 2
                        },
                        new
                        {
                            ProductId = 17,
                            TagId = 3
                        },
                        new
                        {
                            ProductId = 17,
                            TagId = 6
                        },
                        new
                        {
                            ProductId = 18,
                            TagId = 5
                        },
                        new
                        {
                            ProductId = 18,
                            TagId = 6
                        },
                        new
                        {
                            ProductId = 19,
                            TagId = 3
                        },
                        new
                        {
                            ProductId = 19,
                            TagId = 6
                        },
                        new
                        {
                            ProductId = 20,
                            TagId = 5
                        },
                        new
                        {
                            ProductId = 20,
                            TagId = 6
                        });
                });

            modelBuilder.Entity("TechVault.API.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<byte>("Rating")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId", "ProductId")
                        .IsUnique();

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("TechVault.API.Models.WishlistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId", "ProductId")
                        .IsUnique();

                    b.ToTable("WishlistItems");
                });

            modelBuilder.Entity("TechVault.API.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("varchar(96)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Gaming",
                            Slug = "gaming"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Professional",
                            Slug = "professional"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Wireless",
                            Slug = "wireless"
                        },
                        new
                        {
                            Id = 4,
                            Name = "RGB",
                            Slug = "rgb"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Budget",
                            Slug = "budget"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Pro",
                            Slug = "pro"
                        });
                });

            modelBuilder.Entity("TechVault.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("IdentityUserId")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IdentityUserId")
                        .IsUnique();

                    b.HasIndex("Role");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TechVault.API.Models.Address", b =>
                {
                    b.HasOne("TechVault.API.Models.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TechVault.API.Models.CartItem", b =>
                {
                    b.HasOne("TechVault.API.Models.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TechVault.API.Models.Category", b =>
                {
                    b.HasOne("TechVault.API.Models.Category", "ParentCategory")
                        .WithMany("ChildCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("TechVault.API.Models.Order", b =>
                {
                    b.HasOne("TechVault.API.Models.Address", "ShippingAddress")
                        .WithMany()
                        .HasForeignKey("ShippingAddressId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TechVault.API.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ShippingAddress");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TechVault.API.Models.OrderItem", b =>
                {
                    b.HasOne("TechVault.API.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechVault.API.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TechVault.API.Models.Payment", b =>
                {
                    b.HasOne("TechVault.API.Models.Order", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("TechVault.API.Models.Product", b =>
                {
                    b.HasOne("TechVault.API.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TechVault.API.Models.ProductTag", b =>
                {
                    b.HasOne("TechVault.API.Models.Product", "Product")
                        .WithMany("ProductTags")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechVault.API.Models.Tag", "Tag")
                        .WithMany("ProductTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("TechVault.API.Models.Review", b =>
                {
                    b.HasOne("TechVault.API.Models.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechVault.API.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TechVault.API.Models.WishlistItem", b =>
                {
                    b.HasOne("TechVault.API.Models.Product", "Product")
                        .WithMany("WishlistItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechVault.API.Models.User", "User")
                        .WithMany("WishlistItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TechVault.API.Models.Category", b =>
                {
                    b.Navigation("ChildCategories");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("TechVault.API.Models.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("TechVault.API.Models.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderItems");

                    b.Navigation("ProductTags");

                    b.Navigation("Reviews");

                    b.Navigation("WishlistItems");
                });

            modelBuilder.Entity("TechVault.API.Models.Tag", b =>
                {
                    b.Navigation("ProductTags");
                });

            modelBuilder.Entity("TechVault.API.Models.User", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Orders");

                    b.Navigation("Reviews");

                    b.Navigation("WishlistItems");
                });
#pragma warning restore 612, 618
        }
    }
}
